### ISSUE TITLE
Remove post type from permalink

### ISSUE THREAD

**Issue by erralb** [ThemeFuse/Unyson-Portfolio-Extension#4]
Hi, this is more a support request rather than an issue...

Would you have an idea on how to remove the custom post type from the url?

Instead of having `http://my-site.com/project/%fw-portfolio-category%/%postname%/`, having  `http://my-site.com/%fw-portfolio-category%/%postname%/`

After searching and trying various solutions, I could remove the `project` from the url, but it works only if the permalink format is `http://my-site.com/%postname%/`, it is not working with the `%fw-portfolio-category%` format

**Comment by GheorgheP** [comment]
Hi,

Sorry, but there is not a concrete solution, here are some references for doing this:
- https://wordpress.org/support/topic/removing-post-type-from-permalink-for-custom-post-type
- https://wordpress.org/support/topic/remove-permalink-slug-from-custom-post-type
- http://colorlabsproject.com/tutorials/remove-slugs-custom-post-type-url/

By default wordpress removes the post type only for `post` and `page`. That's why we set the post type or taxonomy slug, this will replace the post-type/taxonomy name with a nice slug in the permalink.

This is because, if you'll remove the slug, you can permalink conflicts.
